steps:
  - label: ":linux: x86_64"
    command: .buildkite/steps/build-binary.sh
    env:
      GOOS: linux
      GOARCH: amd64

  - label: ":linux: arm64"
    command: .buildkite/steps/build-binary.sh
    env:
      GOOS: linux
      GOARCH: arm64

  - label: ":windows: x86_64"
    command: .buildkite/steps/build-binary.sh
    env:
      GOOS: windows
      GOARCH: amd64

  # Requires golang 1.17 with support for windows/arm64
  # https://tip.golang.org/doc/go1.17
  # https://github.com/golang/go/issues/36439
  # - label: ":windows: arm64"
  #   command: .buildkite/steps/build-binary.sh
  #   env:
  #     GOOS: windows
  #     GOARCH: arm64

  - label: ":macOS: x86_64"
    command: .buildkite/steps/build-binary.sh
    env:
      GOOS: darwin
      GOARCH: amd64

  - label: ":macOS: arm64"
    command: .buildkite/steps/build-binary.sh
    env:
      GOOS: darwin
      GOARCH: arm64

  - wait

  - label: ":bash: :hammer:"
    plugins:
      docker-compose#v2.2.0:
        run: tests

  - label: "㊙️ git-credentials test"
    command: .buildkite/test_credentials.sh