steps:
  - label: ":bash: :hammer:"
    plugins:
      docker-compose#v2.2.0:
        run: tests

  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v1.0.0:
        name: s3-secrets

  - label: "㊙️ git-credentials test"
    command: .buildkite/test_credentials.sh
    plugins:
      ${BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
        bucket: "${TEST_BUCKET}"